### ISSUE TITLE
Heroku Removing Free Tier

### ISSUE THREAD

**Issue by matsinet** [savvy-coders/sc-curriculum#352]
**Is your feature request related to a problem? Please describe.**
Heroku is removing their free tier which will remove the option for hosting our API servers for the supporting apps and student implementations for sections 8 & 9 as well as capstone projects.
Heroku is going to offer a "student tier" in 2023 to be announced in Sept 2022.   We will need to understand what the requirements are for that service to determine if we can use it.

**Describe the solution you'd like**
A solution that allows the node.js/express API server to be hosted online and allow Netlify SPA to access it.

Additional updates were made for the 2023-01 orientation.

**Update the curriculum and repositories respectively**
Please add pull request links here as each one is created
- [ ] Update [Curriculum](https://github.com/savvy-coders/sc-curriculum)
  - [x] PR development branch [PR 392](https://github.com/savvy-coders/sc-curriculum/pull/392)
- [ ] Update [Teacher's Guide](https://github.com/savvy-coders/sc-js-teachers-guide)
  - [x] PR development branch [PR 21](https://github.com/savvy-coders/sc-js-teachers-guide/pull/21)

**Comment by matsinet** [comment]
[Caprover](https://caprover.com/) is a possible self-hosted option.

**Comment by matsinet** [comment]
I have implemented the Express & Mongo SPA example on repl.it.   It is more clunky than Heroku but it might be a solution for future cohorts if another solution is not found.
https://replit.com/@MattThomas6/SPA-example-with-Express-and-Mongo
You are required to create secrets that provide the MONGODB connection string to start the instance.

**Comment by drod1107** [comment]
I now have a frontend for the Class SPA set up on Netlify here:

[https://infallible-wiles-8c752c.netlify.app/](https://infallible-wiles-8c752c.netlify.app/)

This is connected to a live backend hosted on railway.app

[https://backendhostingtestspa.up.railway.app/pizzas](https://backendhostingtestspa.up.railway.app/pizzas)

I looked at the three most common/popular results I could find that seemed very comparable in regard to learning curve vs Heroku. One was just outright impossible to use without registering a credit card. The other two I attempted simultaneously while also attempting setting up on Heroku for the first time in a while. Heroku was easy as always, and Render.com took an excessive amount of troubleshooting for me; I still haven't quite gotten the API working properly; I believe it's a CORS error. *shudders*

I'm personally backing railway.app because it was the easiest to get started with, offers a ton of flexibility, does not require you to put in a credit card to start hosting and offers enough free hosting that no one should have their apps shut down, and there is more functionality they offer (whether free or not idk yet) that may be REALLY useful later for our own development efforts and/or python later, etc. including  CLI tools, CI/CD and testing integration, etc.

I'd love feedback on the platforms and any input anyone has on the cost structures comparatively, etc., if they have any such feelings.

**Comment by drod1107** [comment]
That having been said... @matsinet @JohanBester @mjwebb1993 ... I *AM* getting a CORS error that I believe is exactly the one we used to get back in my cohort when we first tried deploying to Netlify, but I don't recall the fix. BE is serving up perfectly if you hit the URL direct on the pizzas path or use postman/insomnia to hit it. BE is healthy. But netlify is throwing the CORS error trying to reach anything at all, and I know it's something dumb I'm overlooking.

My latest code is pushed up and I'm moving this to review for a second set of eyes please! Thanks!

**Comment by matsinet** [comment]
After review and implementing the Express & MongoDB example repo on render.com @matsinet has decided as of the October 2022 cohort that is what will be used forward until an AWS or Google Cloud Services alternative can be found.
